### ISSUE TITLE
Is there an option to provide specific regions to estimate the background?

### ISSUE THREAD

**Issue by durrantmm** [asoltis/MutEnricher#1]

**Comment by asoltis** [comment]
Hello,

In the non-coding module, if you use the global background method (default) all regions in your input BED file will be used to calculate background rates. These regions are also all tested. 

In the coding module, you could again use the global background method but also provide a BED file with the -m/--mappable-regions option which includes all the valid regions you wish to test. These regions, however, must overlap the gene boundaries provided in the input GTF when using this module.
