### ISSUE TITLE
Looking for overall enrichment statistics in non-coding regions?

### ISSUE THREAD

**Issue by durrantmm** [asoltis/MutEnricher#2]
I was wondering if there is some way to determine if the regions in a provided BED file are enriched or depleted of somatic mutations on the whole.  A single statistic to summarize the enrichment/depletion of somatic mutations. 

Any ideas?

**Comment by asoltis** [comment]
@durrantmm 

If by "on the whole" you are referring to in comparison to the whole genome, MutEnricher does not natively do this in the noncoding module. A possibility to get close to this may be to include in your input BED file your regions of interest along with similarly sized "random" regions from the genome at some multiple of your true regions (e.g. 10x) to drive the background calculations towards these. Depending on how many regions you are considering, the global method comes closest to this in terms of native functionality as this method computes backgrounds based on all input regions.

**Comment by asoltis** [comment]
@durrantmm 

In terms of depletion statistics, MutEnricher only reports enrichments (e.g. right tail statistics) at this time.
