### ISSUE TITLE
Installation, where is the math_funcs directory?

### ISSUE THREAD

**Issue by Samir-A** [asoltis/MutEnricher#6]
Hello,

I'd first like to say this tool is very well documented and it is perfect for what I need it to do. The only problem I'm having trouble installing in... I am on the Cythonize math functions code step and I am having trouble finding the math_funcs directory. I assume it is a subdirectory in the library package Cython but I cannot find it.

Is it possible I can get helped out?

Thanks

**Comment by asoltis** [comment]
Hello,

Thank you for trying out the code. If you clone the package to your computer with git or if you download the package as a zip (code tab, code drop-down, "Download ZIP"; or via the releases [here](
https://github.com/asoltis/MutEnricher/archive/refs/tags/v1.3.3.zip)) you should see a sub-directory called "math_funcs" containing the code you need. You would then need to enter this folder and run the setup command (i.e. python setup.py build_ext --inplace).

**Comment by Samir-A** [comment]
Thanks for the help I was able to install the tool!
