### ISSUE TITLE
Issue with Output Results Using Custom GTF Files in MutEnricher

### ISSUE THREAD

**Issue by fiou98** [asoltis/MutEnricher#8]
Hello,
I am currently using the MutEnricher program and have encountered an issue with the output results when utilizing my custom GTF files. I created my own GTF files based on both hg19 and hg38 genome references, and the analysis runs successfully without any errors. However, I noticed that the output generated from my custom GTF files contains no genes at all and that the files themselves are empty. The .log file indicates what follows: "Loaded 111309 genes from input GTF file. 0 total non-silent somatic mutations identified in 0 genes. 1294774 total somatic mutations identified in gene limits. Identified 0 candidate hotspots in 0 genes for testing. 0 gene enrichment results reported. 0 gene hotspot enrichment results reported." In contrast, the output from the GTF file provided by the MutEnricher developers includes gene data.
I would like to understand why there is a discrepancy in the output results. Are there specific annotations, filters, or parameters in the provided GTF file that I might be missing in my custom versions? Any guidance on how to ensure that genes are included in the results would be greatly appreciated.

Thank you for your help!

Best regards,
André Fiou

**Comment by asoltis** [comment]
Hi Andre,

Can you answer/check a few things:
- are you using VCF files from WGS or restricted (e.g. WES) data?
- to what genome are your input files (VCFs) aligned? 
- Is there a mismatch between the genome used for alignment and the one used in the custom GTF that is producing the 0 gene output?
- Can you share at least a portion of your custom GTF for me to look at any issues? 

Anthony

**Comment by fiou98** [comment]
Sure! 
- As a preliminary test, I used the sample VCF files provided by you. I ran these analyses with my own custom GTF files based on both the hg19 and hg38 genome references. This allowed me to observe how the program handles the data and to compare the outcomes obtained from using different genome references. Both cases reported the message I attached you in the first message.
- To extend the test, I used some of my own sample files, aligned with the hg38 genome reference to check if my aligned samples would produce similar results.
- I did not encounter any mismatch issues between the genome references. Specifically, I used the hg19 genome reference for your sample VCFs and the hg38 reference for my own samples, ensuring that each set of data was aligned with the correct reference genome.
- Here I attach you a portion of my custom GTFs for both hg38 and hg19: 
<img width="818" alt="hg_38 and hg_19" src="https://github.com/user-attachments/assets/272c3229-979f-42e5-83f7-62d12f0bd971">

Let me know if you have other questions
Thanks 

André

**Comment by asoltis** [comment]
At first glance, the GTFs look fine, but I'm not sure why you would run mixed genome alignment tests (the test VCFs are aligned to hg19, so there is no reason to run the hg38 GTF with these). Regardless, in your test output it looks like the coding analysis reported mutations within the gene limits, but found no non-silent mutations - this would suggest an issue of variant annotation and/or their definitions provided to the code. What software did you use to perform variant annotation, and can you provide the command line run you are using? 

Also, I'm not fully clear on this, but are you saying your custom hg19 GTF did not work with the provided sample VCFs?

**Comment by fiou98** [comment]
I performed a mixed alignment as a test, conscious of the fact that this couldn't work. 
My custom hg19 GTF file didn’t work with your test VCFs, which suggests that the issue may be related with the GTF file itself, as reflected in the different output.
The command line I am using is the following one:
python ~/MutEnricher/mutEnricher.py coding ~/MutEnricher/example_data/annotation_files/hg19_noYM ~/MutEnricher/example_data/vcf_files.txt --anno-type nonsilent_terms.txt -o ~/MutEnricher/output_files/my_GTF_test --prefix test_global

**Comment by asoltis** [comment]
Andre,

Can you share your hg19 GTF with me so I can have a look at it on my end? Also - what format of input data are you using for your own data? If VCF, what annotator have you used for identifying non-silent mutations in these? 

Anthony

**Comment by asoltis** [comment]
Andre,

Thinking about this further, I actually think the issue is mismatch between the gene names (gene ids) in your GTF files and what is annotated in the gene fields in the test VCFs. MutEnricher's coding analysis not only checks the genomic coordinates of mutations, but also the gene id/name when looking for nonsilent variants. Thus, I'd recommend annotating your VCFs according to the GTF file(s) you plan to use in your analysis. 

Anthony

**Comment by fiou98** [comment]
Hi Anthony, 
after several attempts I solved this issue and now the tools is running with my samples. Thanks for your advice!

André

**Comment by asoltis** [comment]
Glad to hear, Andre. I hope the tool works well for you!
